//---------------------------------------------------------------
// ç¹§ï½¿ç¹§ï½¤ç¹åŒ»Îç¹æ§­ãƒ­ç¹ï½¼ç¹§ï½¸ç¹ï½£ç¹ï½¼ [ MatchingManager.cs ]
// Author:Kenta Nakamoto
// Data:2024/12/10
// Update:2025/01/30
//---------------------------------------------------------------
using KanKikuchi.AudioManager;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class MatchingManager : MonoBehaviour
{
    //-------------------------------------------------------
    // ç¹è¼”ã…ç¹ï½¼ç¹ï½«ç¹‰

    /// <summary>
    /// ç¹åŠ±Îç¹§ï½¤ç¹§ï½¹ç¹†ãƒ¼ç¹§ï½¸ID
    /// </summary>
    private int playStageID = 0;

    /// <summary>
    /// ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°ç¹†ããç¹§ï½¹ç¹åŒ»ãŒç¹æ‚¶ãšç¹§ï½§
    /// </summary>
    [SerializeField] private GameObject matchingTextObj;

    /// <summary>
    /// ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°è³å¾¡ï½º†ããƒ¦ç¹§ï½­ç¹§ï½¹ç¹åŒ»ãŒç¹æ‚¶ãšç¹§ï½§
    /// </summary>
    [SerializeField] private GameObject completeTextObj;

    /// <summary>
    /// ç¹ï½«ç¹ï½¼ç¹ ç¹ï½¢ç¹‡ãÎè­¬ï½¼é‚å’²ç•‘
    /// </summary>
    [SerializeField] private RoomModel roomModel;

    /// <summary>
    /// ç¹§ï½­ç¹ï½£ç¹ï½³ç¹§ï½»ç¹ï½«ç¹æ‡Šã¡ç¹ï½³ç¹§ï½ªç¹æ‚¶ãšç¹§ï½§
    /// </summary>
    [SerializeField] private GameObject cancelObj;

    /// <summary>
    /// ç¹§ï½­ç¹ï½£ç¹ï½³ç¹§ï½»ç¹ï½«ç¹æ‡Šã¡ç¹ï½³
    /// </summary>
    [SerializeField] private Button cancelButton;

    /// <summary>
    /// éœ†é¡˜ãƒ¬è­ï½¯
    /// </summary>
    [SerializeField] private Transform carBG;

    //-------------------------------------------------------
    // ç¹ï½¡ç¹§ï½½ç¹ƒããƒ©

    /// <summary>
    /// è›»æ™„æ‚„èœƒï½¦é€…†
    /// </summary>
    async void Start()
    {
        roomModel.OnMatchingUser += OnMatchingUser;     // ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°è³å¾¡ï½º†é€å¤‚è¡

        Invoke("StartMatching",2.0f);
    }

    /// <summary>
    /// è³å£½æ‚„è­–ï½´è­ï½°èœƒï½¦é€…†
    /// </summary>
    private void FixedUpdate()
    {
        // éœ†é¡”åˆ¤èœ’ä¸Šï½’è—æ§­â˜†
        carBG.localEulerAngles += new Vector3(0,0,1.0f);
    }

    /// <summary>
    /// ç¹§ï½­ç¹ï½£ç¹ï½³ç¹§ï½»ç¹ï½«ç¹æ‡Šã¡ç¹ï½³
    /// </summary>
    public async void OnCancelButton()
    {
        // SEèœ€å’²å‡½
        SEManager.Instance.Play(SEPath.TAP_BUTTON);

        cancelButton.interactable = false;

        // è›»‡æå¦™ (é­ƒæ‚¶Â°ç¹§ç‰™ï½¸ï½°ç¸ºï½£ç¸ºï½¦ç¸ºé˜ªâ—†ç¹§å³¨ã™ç¹ï½¼ç¹ï½³é˜ï½»èœè¼”â†“ç¸ºå¶ï½‹)
        await roomModel.DisconnectionAsync();

        // ç¹ï½¡ç¹ä¹Î—ç¹ï½¼ç¹§ï½·ç¹ï½¼ç¹ï½³ç¸ºï½«é©•ï½·é˜ï½»
        Initiate.DoneFading();
        Initiate.Fade("2_MenuScene", Color.white, 2.5f);

        Debug.Log("ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°è³ï½­è±ï½¢");
    }

    /// <summary>
    /// ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°è³å¾¡ï½º†é€å¤‚è¡èœ¿å¶ºï½¿ï½¡è­ã‚…®èœƒï½¦é€…†
    /// </summary>
    /// <param name="roomName"></param>
    private async void OnMatchingUser(string roomName,int stageID)
    {
        roomModel.RoomName = roomName;  // é€‹ï½ºé™¦å¾Œï¼†ç¹§å¾Œâ—†ç¹ï½«ç¹ï½¼ç¹ èœ·é˜ªï½’è«æ™ï½­˜
        playStageID = stageID;          // ç¹§ï½¹ç¹†ãƒ¼ç¹§ï½¸IDç¹§å‰ƒï½¿æ™ï½­˜

        // SEèœ€å’²å‡½
        SEManager.Instance.Play(SEPath.MATCHING_COMPLETE);
        // é™¦ï½¨é‰ï½ºè›»‡æå´›
        cancelObj.SetActive(false);
        matchingTextObj.SetActive(false);
        completeTextObj.SetActive(true);

        // é¨¾€èœƒï½º
        await roomModel.ExitAsync();

        StartCoroutine("TransGmaeScene");

        Debug.Log("ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°è³å¾¡ï½º†");
    }

    /// <summary>
    /// ç¹§ï½²ç¹ï½¼ç¹ ç¹§ï½·ç¹ï½¼ç¹ï½³é©•ï½·é˜ï½»
    /// </summary>
    /// <returns></returns>
    private IEnumerator TransGmaeScene()
    {
        // 1é˜è²ï½¾…ãâ–²ç¸ºï½¦ç¹§ï½³ç¹ï½«ç¹ï½¼ç¹âˆšÎ¦è³ï½­è­ï½­
        yield return new WaitForSeconds(1.2f);

        // playStageIDç¸ºï½«è ¢æ‡ŠÂ§ç¸ºï½¦èŸ‡ï½¾è ¢æ‡Šâ˜†ç¹§ä¹ã”ç¹ï½¼ç¹ ç¹§ï½·ç¹ï½¼ç¹ï½³ç¸ºï½«é©•ï½·é˜ï½»
        Initiate.DoneFading();
        Initiate.Fade(playStageID.ToString() + "_OnlinePlayScene", Color.white, 2.5f);
    }

    /// <summary>
    /// ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°é«¢å¥ï½§å¥‡¦é€…†
    /// </summary>
    private async void StartMatching()
    {
        // è¬—ï½¥é‚¯š
        await roomModel.ConnectAsync();
        // ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°
        await roomModel.JoinLobbyAsync(UserModel.Instance.UserId);
        // ç¹§ï½­ç¹ï½£ç¹ï½³ç¹§ï½»ç¹ï½«ç¹æ‡Šã¡ç¹ï½³è­›ç‰™æŸ‘è›¹–
        cancelButton.interactable = true;

        Debug.Log("ç¹æ§­ãƒ£ç¹âˆšÎ¦ç¹§ï½°é«¢å¥ï½§‹");
    }
}
