//---------------------------------------------------------------
// è‰æ‚¶ƒ—ç¹ï½¬ç¹§ï½¤ç¹ï½¤ç¹ï½¼ç¹æ§­ãƒ­ç¹ï½¼ç¹§ï½¸ç¹ï½£ç¹ï½¼ [ OtherPlayerManager.cs ]
// Author:Kenta Nakamoto
// Data:2024/12/09
// Update:2024/12/16
//---------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class OtherPlayerManager : MonoBehaviour
{
    //=====================================
    // ç¹è¼”ã…ç¹ï½¼ç¹ï½«ç¹‰

    /// <summary>
    /// è®–æ»‰ï½½è–™â†“é«¢ï½¢é¨¾ï½£ç¸ºå¶ï½‹è¬—ï½¥é‚¯å””D
    /// </summary>
    public Guid ConnectionID { get; set; }

    /// <summary>
    /// è®–æ»‰ï½½è–™â†“é«¢ï½¢é¨¾ï½£ç¸ºå¶ï½‹ç¹ï½¦ç¹ï½¼ç¹§ï½¶ç¹ï½¼èœ·
    /// </summary>
    public string UserName { get; set; }

    /// <summary>
    /// èœ¿ã‚‡åˆˆé¬††
    /// </summary>
    public int JoinOrder { get; set; }

    /// <summary>
    /// ç¹§ï½¿ç¹ï½¼ç¹æ‡Šãƒ±ç¹ï½¼ç¹†ãã…ç¹§ï½¯ç¹ï½«
    /// </summary>
    [SerializeField] private ParticleSystem turboParticle;

    /// <summary>
    /// ç¹å³¨Îœç¹è¼”ãƒ¨ç¹ä»£ƒ¼ç¹†ãã…ç¹§ï½¯ç¹ï½«
    /// </summary>
    [SerializeField] private ParticleSystem driftParticle;

    /// <summary>
    /// ç¹§ï½¿ç¹§ï½¤ç¹åŒ»Îç¹§ï½·ç¹ï½¼ç¹ï½³é€•ï½¨ç¹§ï½³ç¹ï½©ç¹§ï½¤ç¹€ç¹ï½¼
    /// </summary>
    [SerializeField] private GameObject titleCollider;

    //=====================================
    // ç¹ï½¡ç¹§ï½½ç¹ƒããƒ©

    /// <summary>
    /// è›»æ™„æ‚„èœƒï½¦é€…†
    /// </summary>
    void Start()
    {
        if(SceneManager.GetActiveScene().name == "1_TitleScene")
        {   // ç¹§ï½¿ç¹§ï½¤ç¹åŒ»Îç¹§ï½·ç¹ï½¼ç¹ï½³ç¸ºï½®ç¸ºï½¿è­›ç‰™æŸ‘
            titleCollider.SetActive(true);
        }
    }

    /// <summary>
    /// è³€è³å£½å³©è­ï½°èœƒï½¦é€…†
    /// </summary>
    void FixedUpdate()
    {
        
    }

    /// <summary>
    /// ç¹§ï½¿ç¹ï½¼ç¹æ‡·†é€•æº·‡¦é€…†
    /// </summary>
    /// <param name="flag"></param>
    public void playTurbo(bool flag)
    {
        if (flag)
        {   // èœ€å’²å‡½
            if(!turboParticle.isPlaying) turboParticle.Play();
        }
        else
        {   // è››æ‡ˆï½­ï½¢
            if(turboParticle.isPlaying) turboParticle.Stop();
        }
    }

    /// <summary>
    /// ç¹å³¨Îœç¹è¼”ãƒ¨èœ€å’²å‡½èœƒï½¦é€…†
    /// </summary>
    /// <param name="flag"></param>
    public void playDrift(bool flag)
    {
        if (flag)
        {
            if(!driftParticle.isPlaying) driftParticle.Play();
        }
        else
        {
            if(driftParticle.isPlaying) driftParticle.Stop();
        }
    }

    /// <summary>
    /// ç¹§ï½³ç¹ï½©ç¹§ï½¤ç¹€ç¹ï½¼è¬—ï½¥éš—ï½¦è­ã‚‡‡¦é€…†
    /// </summary>
    /// <param name="collision"></param>
    private void OnTriggerEnter(Collider collision)
    {
        if (collision.gameObject.tag == "TitleObj")
        {
            // é–¾ï½ªéœ„ï½«ç¹§è²ç‚é«¯ï½¤
            Destroy(this.gameObject);
        }

        if (collision.gameObject.tag == "Goal")
        {
            Destroy(this.gameObject);
        }
    }
}
